### ISSUE TITLE
Infografia SDLC Yael

### ISSUE THREAD

**Issue by YaelStO** [SistemasTecTlaxiaco/YaelSantiago11#1]
[
[Ciclo de vida de desarrollo de software.pdf](https://github.com/SistemasTecTlaxiaco/YaelSantiago11/files/12495192/Ciclo.de.vida.de.desarrollo.de.software.pdf)
](url)

**Comment by luzm23** [comment]
19/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
